# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
