# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='comments',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
