# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161121_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.CharField(choices=[('8 ounces', '8oz'), ('9 ounces', '9oz'), ('10 ounces', '10oz'), ('11 ounces', '11oz'), ('12 ounces', '12oz'), ('1 pound', '1lbs'), ('5 pounds', '5lbs')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
