# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161123_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.CharField(choices=[('8 ounces', '8oz'), ('9 ounces', '9oz'), ('10 ounces', '10oz'), ('11 ounces', '11oz'), ('12 ounces', '12oz'), ('1 pound', '1lbs'), ('5 pounds', '5lbs')], max_length=20),
        ),
    ]
