# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161123_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='price',
            new_name='price_per_oz',
        ),
    ]
