# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161123_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
    ]
