# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_inventoryitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='price_per_oz',
            new_name='price_12_oz',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_1_lbs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_5_lbs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.CharField(choices=[('12oz', '12oz'), ('1lbs', '1lbs'), ('5lbs', '5lbs')], max_length=20),
        ),
    ]
