# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='production',
            new_name='production_complete',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='roaster',
            new_name='production_seen',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='shipping',
            new_name='roaster_complete',
        ),
        migrations.AddField(
            model_name='invoice',
            name='roaster_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_seen',
            field=models.BooleanField(default=False),
        ),
    ]
