# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161126_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
