# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161126_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
