# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20161127_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
