# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
