# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_inventoryitem_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_discount',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
